name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  all-status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - yaml-lint
      - markdown-lint
      - shell-lint
      - action-lint
      - dotenv-lint
      - type-check
      - lint-check
      - vitest-test
    steps:
      - name: All status check
        run: echo "All status check passed"

  yaml-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1.22.0
        with:
          level: warning
          yamllint_flags: -c .yamllint .
          fail_on_error: true

  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-markdownlint@6f0e0e8703a9e840ffefa37a2775832c51c1c640 # v0.28.0
        with:
          level: warning
          fail_on_error: true

  shell-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          level: warning
          fail_on_error: true
      - uses: reviewdog/action-shfmt@c5e3ba7497c338866921924691aef4fa18bc1fe0 # v1.1.0
        with:
          level: warning
          fail_on_error: true

  action-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
        with:
          level: warning
          fail_on_error: true

  dotenv-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: dotenv-linter/action-dotenv-linter@afde61cfda2ecffe7bea35837b6f20b956c88689 # v3.0.0
        with:
          dotenv_linter_flags: --skip UnorderedKey
          fail_on_error: true

  type-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: shiron-dev/actions/setup-node@8780bd20d1ef046844aa1a1c2e9d96fefaa1384b # v1.7.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run typecheck
        run: pnpm run typecheck

  lint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: shiron-dev/actions/setup-node@8780bd20d1ef046844aa1a1c2e9d96fefaa1384b # v1.7.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint

  vitest-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: shiron-dev/actions/setup-node@8780bd20d1ef046844aa1a1c2e9d96fefaa1384b # v1.7.0
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run test
        run: pnpm run test
