name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Release please
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          release-type: node
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    steps:
      - uses: actions/checkout@v6
      - uses: shiron-dev/actions/setup-node@d66efb301f140b377987e9cb9d49baa97b950765 # v1.6.5
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
# TODO: Add a step to deploy the application
